accounts/urls.py
from django.urls import path, register_converter
from .views import *
from utils import HashIdConverter

register_converter(HashIdConverter, "hashid")

urlpatterns = [
    path('signup/', signupView, name='signup'),
    path('login/', loginView, name='login'),
    path('logout/', logoutUser, name='logout'),
    # ----------------------------------------------------------------------------
    path('staff/', staff, name='staff'),
    path('staff/grid/', staff_grid, name='staff_grid'),
    path('staff/list/', staff_list, name='staff_list'),
    path('staff/create/', create_staff, name='create_staff'),
    path('staff/<hashid:pk>/', staff_details, name='staff_details'),
    path('staff/<hashid:pk>/edit/', edit_staff, name='edit_staff'),
    path('staff/<hashid:pk>/profile/edit/',
         edit_staff_profile, name='edit_staff_profile'),
    path('staff/<hashid:pk>/wallet/create/',
         create_staff_wallet, name='create_staff_wallet'),
]

base/urls.py
from django.urls import path, register_converter
from .views import *
from utils import HashIdConverter

register_converter(HashIdConverter, "hashid")

urlpatterns = [
    path('', home, name='home'),
    path('stores/', stores, name='stores'),
    path('stores/list/', stores_list, name='stores_list'),
    path('stores/create/', create_store, name='create_store'),
    path('stores/<hashid:pk>/', store_details, name='store_details'),
    path('stores/<hashid:pk>/edit/', edit_store, name='edit_store'),
    path('stores/<hashid:pk>/transactions/',
         store_transactions, name='store_transactions'),
    path('stores/<hashid:pk>/stock/', store_stock, name='store_stock'),
    # ----------------------------------------------------------------------------
    path('products/', products, name='products'),
    path('products/stocks/', product_stocks, name='product_stocks'),
    path('products/create/', create_product, name='create_product'),
    path('products/list/', products_list, name='products_list'),
    path('products/grid/', products_grid, name='products_grid'),
    path('products/filter/', filter_products, name='filter_products'),
    path('products/<hashid:pk>/', product_details, name='product_details'),
    path('products/<hashid:pk>/edit/', edit_product, name='edit_product'),
    # ----------------------------------------------------------------------------
    path('entities/types/list/', entity_types_list, name='entity_types_list'),
    path('entities/types/create/', create_entity_type, name='create_entity_type'),
    path('entities/types/<hashid:pk>/edit/', edit_entity_type, name='edit_entity_type'),
    # ----------------------------------------------------------------------------
    path('units/list/', units_list, name='units_list'),
    path('units/create/', create_unit, name='create_unit'),
    path('units/<hashid:pk>/edit/', edit_unit, name='edit_unit'),
    # ----------------------------------------------------------------------------
    path('stock/', stock, name='stock'),
    # ----------------
    path('stock/overview/', stock_overview, name='stock_overview'),
    path('stock/inventories/', inventories, name='inventories'),
    path('stock/inventories/create', create_inventory, name='create_inventory'),
    path('stock/inventories/<hashid:pk>/', inventory_details, name='inventory_details'),
    path('stock/inventories/<hashid:pk>/edit/', edit_inventory, name='edit_inventory'),
    # ----------------
    path('stock/products/list/', prod_stock_list, name='prod_stock_list'),
    path('stock/products/create/', create_prod_stock, name='create_prod_stock'),
    path('stock/products/filter/<str:pk>/', filter_prod_stock, name='filter_prod_stock'),
    path('stock/products/<hashid:pk>/',
         prod_stock_details, name='prod_stock_details'),
    path('stock/products/<hashid:pk>/edit/',
         edit_prod_stock, name='edit_prod_stock'),
    path('stock/products/<hashid:pk>/stocks/', prod_stocks, name='prod_stocks'),
    # ------------------------------
    path('stock/ops/details/<hashid:pk>/',
         stock_ops_details, name='stock_ops_details'),
    path('stock/ops/edit/<hashid:pk>/', edit_stock_ops, name='edit_stock_ops'),
    path('stock/ops/create/<str:pk>/', create_stock_ops, name='create_stock_ops'),
    path('stock/ops/<str:pk>/', stock_ops, name='stock_ops'),
    # ----------------
    path('stock/ops/<hashid:pk>/info/',
         stock_ops_info, name='stock_ops_info'),
    path('stock/ops/<hashid:pk>/items/',
         stock_ops_items, name='stock_ops_items'),
    path('stock/ops/<hashid:pk>/create/item/',
         create_stock_ops_item, name='create_stock_ops_item'),
    path('stock/ops/<hashid:pk>/edit/item/',
         edit_stock_ops_item, name='edit_stock_ops_item'),
    # ----------------------------------------------------------------------------
    path('cart/', cart, name='cart'),
    path('cart/add_item/', add_to_cart, name='add_to_cart'),
    path('cart/remove_item/', remove_from_cart, name='remove_from_cart'),
    path('cart/clear_item/', clear_item, name='clear_item'),
    path('cart/clear_cart/', clear_cart, name='clear_cart'),
    # ----------------------------------------------------------------------------
    path('sales/', sales, name='sales'),
    path('sales/table/', sales_table, name='sales_table'),
    path('sales/pos/', sale_point, name='sale_point'),
    path('sales/pos/grid/', sale_point_grid, name='sale_point_grid'),
    path('sales/checkout/', checkout, name='checkout'),
    path('sales/stock/filter/', filter_sale_stock, name='filter_sale_stock'),
    # ----------------------------------------------------------------------------
    path('sales/create/', create_sale, name='create_sale'),
    path('sales/<hashid:pk>/', sale_details, name='sale_details'),
    path('sales/<hashid:pk>/edit/', edit_sale, name='edit_sale'),
    path('sales/<hashid:pk>/info/', sale_info, name='sale_info'),
    path('sales/<hashid:pk>/items/list/', sale_items, name='sale_items'),
    path('sales/<hashid:pk>/items/create/',
         create_sale_item, name='create_sale_item'),
    path('sales/items/<hashid:pk>/edit/',
         edit_sale_item, name='edit_sale_item'),
    path('sales/<hashid:pk>/transactions/create/',
         create_sale_transaction, name='create_sale_transaction'),
    # ----------------------------------------------------------------------------
    path('purchases/', purchases, name='purchases'),
    path('purchases/create/<str:pk>/', create_purchase, name='create_purchase'),
    path('purchases/list/<str:pk>/', purchases_list, name='purchases_list'),
    path('purchases/<hashid:pk>/edit/', edit_purchase, name='edit_purchase'),
    path('purchases/<hashid:pk>/info/', purchase_info, name='purchase_info'),
    # --------------------------
    path('purchases/items/<hashid:pk>/list/',
         purchase_items, name='purchase_items'),
    path('purchases/items/<hashid:pk>/create/',
         create_purchase_item, name='create_purchase_item'),
    path('purchases/items/<hashid:pk>/edit/',
         edit_purchase_item, name='edit_purchase_item'),
    # --------------------------
    path('purchases/<hashid:pk>/create/transaction/',
         create_purchase_transaction, name='create_purchase_transaction'),
    path('purchases/<hashid:pk>/',
         purchase_details, name='purchase_details'),
    # ----------------------------------------------------------------------------
    path('clients/', clients, name='clients'),
    path('clients/create/', create_client, name='create_client'),
    path('clients/list/', clients_list, name='clients_list'),
    path('clients/filter/', filter_clients, name='filter_clients'),
    path('clients/<hashid:pk>/', client_details, name='client_details'),
    path('clients/<hashid:pk>/edit/', edit_client, name='edit_client'),
    path('clients/<hashid:pk>/purchases/',
         client_purchases, name='client_purchases'),
    path('clients/<hashid:pk>/purchases/filter/',
         filter_client_purchases, name='filter_client_purchases'),
    # ----------------------------------------------------------------------------
    path('suppliers/', suppliers, name='suppliers'),
    path('suppliers/create/', create_supplier, name='create_supplier'),
    path('suppliers/list/', suppliers_list, name='suppliers_list'),
    path('suppliers/filter/', filter_suppliers, name='filter_suppliers'),
    path('suppliers/<hashid:pk>/', supplier_details, name='supplier_details'),
    path('suppliers/<hashid:pk>/edit/', edit_supplier, name='edit_supplier'),
    # ----------------------------------------------------------------------------
    path('parameters/', parameters, name='parameters'),
    path('parameters/categories/list/', categories_list, name='categories_list'),
    path('parameters/categories/create/', create_category, name='create_category'),
    path('parameters/categories/<hashid:pk>/edit/', edit_category, name='edit_category'),
    # --------------------------
    path('parameters/lots/list/', lots_list, name='lots_list'),
    path('parameters/lots/create/', create_lot, name='create_lot'),
    path('parameters/lots/<hashid:pk>/', lot_details, name='lot_details'),
    path('parameters/lots/<hashid:pk>/edit/', edit_lot, name='edit_lot'),
    # --------------------------
    path('parameters/families/load/', load_families, name='load_families'),
    path('parameters/families/list/', families_list, name='families_list'),
    path('parameters/families/create/', create_family, name='create_family'),
    path('parameters/families/<hashid:pk>/edit/',
         edit_family, name='edit_family'),
    # --------------------------
    path('finances/', finances, name='finances'),
    path('finances/reports/', reports, name='reports'),
    path('finances/treasury/', treasury, name='treasury'),
    # --------------------------
    path('finances/cashdesks/create/', create_cashdesk, name='create_cashdesk'),
    path('finances/cashdesks/list/', cashdesks_list, name='cashdesks_list'),
    path('finances/cashdesks/<hashid:pk>/',
         cashdesk_details, name='cashdesk_details'),
    path('finances/cashdesks/<hashid:pk>/edit/',
         edit_cashdesk, name='edit_cashdesk'),
    # --------------------------
    path('finances/cashdesks/transactions/<hashid:pk>/',
         desk_transactions, name='desk_transactions'),
    # --------------------------
    path('finances/cashdesks/desk_closings/list/<hashid:pk>/',
         desk_closings_list, name='desk_closings_list'),
    path('finances/cashdesks/desk_closings/details/<hashid:pk>/',
         desk_closing_details, name='desk_closing_details'),
    path('finances/cashdesks/desk_closings/<hashid:pk>/',
         create_closing_receipt, name='create_closing_receipt'),
    path('finances/cashdesks/desk_closings/<hashid:pk>/create/',
         create_desk_closing, name='create_desk_closing'),
    path('finances/cashdesks/desk_closings/<hashid:pk>/edit/',
         edit_desk_closing, name='edit_desk_closing'),

pronap_admin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

handler404 = 'base.views.not_found'

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from django.urls import reverse
from datetime import date
from django.utils import timezone
from utils import h_encode, h_decode
# from base.models import Company


class Role(models.Model):
    name = models.CharField(db_index=True, unique=True, max_length=255)
    description = models.TextField(default='', null=True, blank=True)
    sec_level = models.IntegerField(default='0')

    def get_hashid(self):
        return h_encode(self.id)

    def __str__(self):
        return self.name


class CustomUserManager(BaseUserManager):
    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('Email must be provided')
        if not password:
            raise ValueError('Password must be prvided')
        user = self.model(email=self.normalize_email(email), **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password, **extra_fields):
        extra_fields.setdefault('is_active', True)
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_active', True)
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self._create_user(email, password, **extra_fields)


class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(db_index=True, unique=True, max_length=255)
    username = models.CharField(
        max_length=255, unique=True, blank=True, null=True)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    phone = models.CharField(max_length=100, unique=True, blank=True, null=True)
    role = models.ForeignKey(
        Role, on_delete=models.CASCADE, blank=True, null=True,)

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        # return f'{self.last_name} {self.first_name}'
        return f' {self.email.split("@")[0]}'

    def get_hashid(self):
        return h_encode(self.id)

    def get_short_name(self):
        return f' {self.email.split("@")[0]}'
    
    def get_full_name(self):
        return f' {self.last_name} {self.first_name}'


genders = (
    ('female', 'Féminin'),
    ('male', 'Masculin'),
)


class Profile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    store = models.OneToOneField('base.Store', blank=True, null=True, on_delete=models.SET_NULL)
    phone = models.CharField(max_length=100, unique=True, blank=True, null=True)
    sex = models.CharField(
        max_length=10, choices=genders, blank=True, null=True)
    image = models.ImageField(
        upload_to='uploads/users/profiles', default='../static/imgs/anon.png', blank=True, null=True)

    def __str__(self):
        return f'{self.user.last_name} {self.user.first_name} - Profile'

    def get_hashid(self):
        return h_encode(self.id)

    def get_absolute_url(self):
        return reverse('profile', kwargs={'pk': self.pk})


class Wallet(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    balance = models.BigIntegerField(default=0)

    def __str__(self):
        return f'{self.user.last_name} balance {self.balance}'

    def get_hashid(self):
        return h_encode(self.id)

    def get_absolute_url(self):
        return reverse('Wallet', kwargs={'pk': self.pk})

accounts/templates/accounts/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script
      src="https://code.jquery.com/jquery-3.7.1.min.js"
      integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="
      crossorigin="anonymous"
    ></script>
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script
      src="https://unpkg.com/htmx.org@1.9.8"
      integrity="sha384-rgjA7mptc2ETQqXoYC3/zJvkU7K/aP44Y+z7xQuJiVnB/422P/Ak+F/AqFR7E4Wr"
      crossorigin="anonymous"
    ></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    <script
      src="https://kit.fontawesome.com/f601cf3e61.js"
      crossorigin="anonymous"
    ></script>
    <script src="{% static 'cart.js' %}" defer="true"></script>
    <script src="{% static 'main.js' %}" defer="true"></script>
    <link href="{% static 'styles.css' %}" rel="stylesheet" />
    <!-- <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Noto+Sans:wght@400;700&display=swap"> -->
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Helvetica:wght@400;700&display=swap"
    />
    <link
      rel="shortcut icon"
      href="{% static 'imgs/logo.png' %}"
      type="image/x-icon"
    />

    <style>
      body {
        /* font-family: 'Noto Sans', sans-serif; */
        font-family: "Helvetica", sans-serif;
        /* font-family: 'Roboto', sans-serif; */
      }
    </style>
    {% if title %}
    <title>Distroplace - {{title}}</title>
    {% else %}
    <title>Distroplace</title>
    {% endif %}
  </head>
  <body
    hx-boost="false"
    hx-headers='{"X-CSRFToken" : "{{ csrf_token }}"}'
    class="h-screen flex flex-col justify-center items-center bg-gray-100"
  >
    {% csrf_token %}
    <!--  -->
    {% if messages %}
    <div class="messages">
      {% for message in messages %}
      <div class="alert {% if message.tags %}{{ message.tags }}{% endif %}">
        {{ message }}
      </div>
      {% endfor %}
    </div>
    {% endif %}

    <section
      class="bg-white p-4 lg:p-6 w-full max-w-5xl rounded mx-auto flex flex-col md:flex-row items-center justify-center gap-8"
    >
      <!-- <i
      class="fa-solid fa-arrow-right-to-bracket text-green-700 text-9xl mx-auto"
    ></i> -->
      <img
        class="h-40 mx-auto mx-auto"
        src="{% static 'imgs/logo.png' %}"
        alt="logo"
      />

      <div
        class="bg-gray-100 rounded p-6 flex-col h-fit w-full max-w-md shadow-md"
      >
        <h1 class="mb-4 text-black text-3xl font-bold">Connexion</h1>
        <form method="POST" class="w-full text-sm">
          {% csrf_token %}
          <div class="flex flex-col mb-2">
            <label for="username">Email</label>
            <input
              type="email"
              name="username"
              class="px-4 py-2 rounded border border-gray-200 focus:border-none focus:outline-none focus:ring-1 focus:ring-lime-300 w-full"
              placeholder="Email"
              required
            />
          </div>
          <div class="flex flex-col mb-4">
            <label for="password">Mots de passe</label>
            <input
              type="password"
              name="password"
              class="px-4 py-2 rounded border border-gray-200 focus:border-none focus:outline-none focus:ring-1 focus:ring-lime-300 w-full"
              placeholder="Mots de passe"
              required
            />
          </div>
          <!-- redirects to intended page -->
          {% if request.GET.next %}
          <input type="hidden" name="next" value="{{request.GET.next}}" />
          {% endif %}
          <div class="flex justify-between items-center gap-2">
            <input
              type="submit"
              value="Se connecter"
              class="mt-2 px-8 py-2 bg-green-700 hover:bg-green-900 text-white rounded cursor-pointer"
            />
            <p class="mt-2">
              Mots de pass oublié?
              <a
                href="{% url 'signup' %}"
                class="text-orange-500 hover:underline"
                >Cliquez ici</a
              >
            </p>
          </div>
        </form>
      </div>
    </section>
  </body>
</html>

accounts/templates/accounts/signup.html
{% extends 'main_plain.html' %} {% load static %} {% block content %}

<section
  class="bg-white p-4 lg:p-6 w-full max-w-5xl rounded-3xl mx-auto flex flex-col md:flex-row items-center justify-center gap-8"
>
  <i class="fa-solid fa-user-plus text-teal-700 text-9xl mx-auto"></i>

  <div class="bg-gray-100 rounded p-6 flex-col h-fit w-full max-w-md shadow-md">
    <h1 class="mb-4 text-black text-3xl font-bold">Inscription</h1>
    <form class="w-full text-sm" method="POST" enctype="multipart/form-data">
      {% csrf_token %} {% for field in form %}
      <div>
        <h3 class="mb-1">{{field.label}}</h3>
        {{field}}
      </div>
      {% endfor %}
      <div class="flex justify-between items-center gap-2">
        <input
          class="mt-2 px-8 py-2 bg-teal-700 hover:bg-teal-900 text-sm text-white rounded-full cursor-pointer"
          type="submit"
          value="S'inscrire"
        />
        <p class="login-wrapper-footer-text mt-2">
          Vous avez déjà un compte?
          <a href="{% url 'login' %}" class="text-yellow-500">Cliquez ici</a>
        </p>
      </div>
    </form>
  </div>
</section>
{% endblock %}

accounts/templates/accounts/staff_card.html
{% load static %}
<!--  -->
<div
  class="h-full flex items-center border bg-white hover:shadow-md rounded overflow-hidden"
>
  {% if not obj.profile.image %}
  <img
    class="h-20 w-20 mx-auto rounded-full object-cover"
    src="{% static 'imgs/anon.png' %}"
    alt="image"
  />
  {% else %}
  <img
    class="h-20 w-20 mx-auto rounded-full object-cover"
    src="{{obj.profile.image.url}}"
    alt="image"
  />
  {% endif %}

  <a
    href="{% url 'staff_details' obj.id %}"
    hx-boost="false"
    class="bg-lime-200 bg-white p-3 h-full w-full flex flex-col gap-1 text-left cursor-pointer"
  >
    <h4 class="text-black font-bold">{{obj.last_name}} {{obj.first_name}}</h4>
    <p class="rounded flex gap-2 items-center text-black text-xs">
      {{obj.role.name}}
    </p>
    <p class="text-sm">{{obj.profile.bio|truncatechars:50}}</p>
  </a>
</div>

accounts/templates/accounts/staff_details.html
{% extends 'main.html' %} {% load static %} {% block content %}
<div class="w-full max-w-7xl mx-auto flex flex-col gap-4">
  <div class="flex justify-between items-center gap-4">
    <a
      class="w-fit px-3 py-2 text-white bg-green-700 hover:bg-green-900 rounded transition-all duration-300"
      href="{% url 'staff' %}"
      >&larr;
    </a>
    <div class="flex gap-3 items-center">
      {% if curr_obj.profile.store %}
      <a
        class="w-fit px-3 py-2 text-black bg-lime-200 hover:bg-lime-300 rounded transition-all duration-300"
        href="{% url 'store_details' curr_obj.profile.store.id %}"
        ><i class="fa-solid fa-store-alt mr-3"></i>Boutique affiliée</a
      >
      {% endif %}
      <!--  -->
      {% if not wallet and user.role.sec_level > 2 %}
      <a
        class="w-fit px-3 py-2 text-black bg-orange-200 hover:bg-orange-300 rounded transition-all duration-300"
        href="{% url 'create_staff_wallet' curr_obj.id %}"
        ><i class="fa-solid fa-wallet mr-3"></i>Nouveau portefeuil</a
      >
      {% endif %}
    </div>
  </div>
  <!--  -->
  <div
    class="p-3 w-full h-full border border-green-900 rounded shadow-lg flex flex-col lg:flex-row items-center gap-4"
  >
    {% if not curr_obj.image %}
    <img
      class="h-40 w-40 bg-white rounded-full object-cover"
      src="{% static 'imgs/anon.png' %}"
      alt="image"
    />
    {% else %}
    <img
      class="h-40 w-40 bg-white rounded-full object-cover"
      src="{{curr_obj.image.url}}"
      alt="image"
    />
    {% endif %}
    <article class="text-gray-700 grid gap-1 w-full">
      <div class="flex justify-between items-center">
        <h4 class="text-black text-2xl font-bold">
          {{curr_obj.last_name}} {{curr_obj.first_name}}
        </h4>
        <div class="flex items-center gap-2">
          <button
            hx-target="#basic_dialog"
            hx-get="{% url 'edit_staff' curr_obj.profile.id %}"
            class="bg-green-700 hover:bg-green-900 rounded py-2 px-4 text-white flex items-center gap-2"
          >
            <small class="hidden xl:inline xl:mr-2"> Compte </small>
            <i class="fa-solid fa-pen text-xs"></i>
          </button>
          {% if user.role.sec_level > 1 %}
          <button
            hx-target="#basic_dialog"
            hx-get="{% url 'edit_staff_profile' curr_obj.profile.id %}"
            class="bg-orange-200 hover:bg-orange-300 rounded py-2 px-4 text-black flex items-center gap-2"
          >
            <small class="hidden xl:inline xl:mr-2"> Profile </small>
            <i class="fa-solid fa-pen-to-square text-xs"></i>
          </button>
          {% endif %}
        </div>
      </div>
      <span class="text-green-700">@{{curr_obj.username}}</span>
      <p>
        <i class="fa-solid fa-venus-mars text-gray-800 mr-3"></i> Sexe :
        <span class="text-black">
          {{curr_obj.profile.get_sex_display|title}}
        </span>
      </p>
      <p>
        <i class="fa-solid fa-phone text-gray-800 mr-3"></i> N° de téléphone :
        <span class="text-black"> {{curr_obj.phone}} </span>
      </p>
      <p>
        <i class="fa-solid fa-user-tie text-gray-800 mr-3"></i> Role :
        <span class="text-black"> {{curr_obj.role.name|title}} </span>
      </p>
    </article>
    <!--  -->
    <div
      class="w-full h-100 bg-green-900 text-white p-4 rounded flex flex-col gap-2"
    >
      <p class="bg-orange-300 rounded p-2 text-black">
        <i class="fa-solid fa-wallet text-orange-700 text-gray-800 mr-3"></i
        >Portefeuil :
        <span class="font-bold"> {{wallet.balance}} CFA </span>
      </p>
      <p>
        <i class="fa-solid fa-scroll text-lime-200 text-gray-800 mr-3"></i
        >Transactions :
        <span class="font-bold">
          {{transactions|length}} | {{trans_aggregate}} CFA
        </span>
      </p>
      <p>
        <i class="fa-solid fa-tags text-lime-200 text-gray-800 mr-3"></i>Ventes
        effectuées :
        <span class="font-bold">
          {{sales|length}} | {{sales_aggregate}} CFA
        </span>
      </p>
      <p>
        <i
          class="fa-solid fa-boxes-packing text-lime-200 text-gray-800 mr-3"
        ></i
        >Stockages effectuées :
        <span class="font-bold">
          {{stocks|length}} | {{stock_aggregate}} CFA
        </span>
      </p>

      <!--------------------------------------- menu tabs buttons --------------------------------------->

      <div
        class="flex justify-between gap-2 text-xs text-black tabbar h-fit w-full max-w-80 lg:max-w-[600px]"
      >
        <button
          class="tabBtn px-4 py-2 bg-white hover:bg-green-700 hover:text-white rounded w-full"
          onclick="openTab(event, 'overview')"
          id="defaultTab"
        >
          <i class="fa-solid fa-chart-bar"></i>
          <span class="ml-2">Stats</span>
        </button>
        <button
          class="tabBtn px-4 py-2 bg-white hover:bg-green-700 hover:text-white rounded w-full"
          onclick="openTab(event, 'sales')"
        >
          <i class="fa-solid fa-tags"></i>
          <span class="ml-2">Ventes</span>
        </button>
        <button
          class="tabBtn px-4 py-2 bg-white hover:bg-green-700 hover:text-white rounded w-full"
          onclick="openTab(event, 'stocks')"
        >
          <i class="fa-solid fa-boxes-packing"></i>
          <span class="ml-2">Stockages</span>
        </button>
      </div>
    </div>
  </div>

  <section class="flex flex-col gap-4">
    <div id="overview" class="tabcontent w-full flex flex-col gap-2"></div>

    <div id="sales" class="tabcontent w-full flex flex-col gap-2"></div>

    <div id="stocks" class="tabcontent w-full flex flex-col gap-2"></div>
  </section>
</div>

{% endblock %}